### ISSUE TITLE
Bump prost prost-types to >= v0.10

### ISSUE THREAD

**Issue by Nazarevsky** [m10io/looking-glass#1]
Since `looking-glass-protobuf` is used in the [monorepo](https://github.com/m10io/mono) and we are trying to resolve [RUSTSEC-2023-0052](https://github.com/m10io/mono/tree/fix/M10-13-Fix-ignore-RUSTSEC-2023-0052) vulnerability, it is requiered to bump tonic to v0.7 in the monorepo. However, here comes some difficulties that are connected with the use of different prost versions when building `.proto` files. To resolve those difficulties it is needed to bump prost and prost-types to >= v0.10

**Comment by J3imip** [comment]
Bumped
